### ISSUE TITLE
Not detecting .njk file extensions

### ISSUE THREAD

**Issue by ArmanNisch** [alohaas/language-nunjucks#14]
I am not entirely sure if this is related to this plugin or a Atom specific setting, but If I rename files to use the .njk (instead of the .nunjucks) file extension, then Atom is not able to detect that the file is a nunjucks template file.

**Comment by puranjayjain** [comment]
@ArmanNisch that issue is long pending in pull request #11. Meanwhile i can suggest you use [this](https://atom.io/packages/atom-language-nunjucks) instead.

**Comment by joelbschwartz** [comment]
@puranjayjain Why didn't you fork this repository to add your changes? I see that you added autocomplete and some additional snippets, which looks great. However, much of the code shows you _copied_ this repository to add the features, instead of forking it. And then you replaced Olivia's name with your own in the copyright, and removed @alohaas as a contributor while retaining the rest of the us?! This goes against the spirit of open source software, not to mention it blatantly violates the attribution requirement of the MIT license.

**Comment by alohaas** [comment]
@joelbschwartz thanks for alerting me to this. It's true that I have been quite busy and have not noticed many of these Issues. I can attend to them now, however.

@puranjayjain in the future I would suggest being more proactive about reaching out to me directly via an @ mention if you are looking for an immediate response, which I usually respond to right away.

**Comment by puranjayjain** [comment]
@joelbschwartz I am pulling my repo right now and totally agree with you

**Comment by alohaas** [comment]
@ArmanNisch I've merged in PR #11 which will autodetect `.nk` file extensions.
