### ISSUE TITLE
the file type extension

### ISSUE THREAD

**Issue by jxintang** [alohaas/language-nunjucks#27]
since my nunjucks file type is *.tpl, so i have to change the filetypes in grammers/(nunjucks templates).cson manually. could you consider adding more filetypes?

```
'fileTypes': [
  'nunjucks'
  'Nunjucks'
  'njk'
  'tpl'
]

```

**Comment by puranjayjain** [comment]
@jxintang we support these file types `*.nunjucks, *.Nunjucks, *.njk`  located here https://github.com/alohaas/language-nunjucks/blob/master/grammars/html%20(nunjucks%20templates).cson#L1 with the first two being the official ones and the last one due to popular community adaption. I am not aware of the `*.tpl` extension. 

So I would like to ask you is it an official or a community extension, if so can you give me a reference to it?
Any other relevant information or discussion is absolutely welcome

**Comment by revelt** [comment]
I agree, `.tpl` is non-standard. Out of curiosity, @jxintang why do you use this extension, instead of usual-ones?

**Comment by frasertmay** [comment]
`.tpl` seems like a very generic file extension so I don't think having it automatically recognised as a Nunjucks file would be a good idea so I'm going to close the issue

**Comment by alohaas** [comment]
Thanks @frasertmay.
