### ISSUE TITLE
Support for VSCode

### ISSUE THREAD

**Issue by york-xtrem** [alohaas/language-nunjucks#28]
This package seems exceptional! Have you thought to move it to VSCode?

Thank you

**Comment by revelt** [comment]
Out of pure curiosity, why would you ever support Micro$oft by using their products?

Personally I'm critical about M$ because they nearly killed the internet in its infancy, then tortured everybody with IE's for two decades and still torture email developers to this day with IE5-age bugs in software as late as Outlook 2017? I'm along the lines of [this](http://www.paulgraham.com/microsoft.html). I code lots of email and in email dev world we're at the same state like web development was in 2007 — it's just pain fixing bugs coming from M$ products.

@york-xtrem do you feel, it isn't hypocritical then to consume Micro$oft products to produce Open Source? Isn't everything we stand for, Open Source, Git, GitHub, JavaScript, free libraries, free software in general, even Macs, came as an opposition to Micro$oft.

**Comment by york-xtrem** [comment]
I do not like Microsoft and its philosophy either. In fact, it is the only product I use. But I think VSCode is a very good editor. It has native features that in atom are packages. I don't think things are black or white, there are grays.

I must assume that you don't use:

- React
- Angular
- Typescript
- Android
- Swift
- ...

Because they are made by companies with dubious morality and ethics, right?

**Comment by revelt** [comment]
I don't mind FB and G, but M$ is pain. You know, IE5 bug which imposed minimum heights of 18px on cells? Well, that bug is present in latest Outlook.. Word's/Trident rendering engine, happening in 2017..

**Comment by york-xtrem** [comment]
They all have a dark side. React is free but has a confusing license. I sometimes make templates for mail and I suffer from Outlook. But that does not stop you from using cool tools like Typescript or VSCode. Lately Microsoft is making an effort to do things right.

**Comment by revelt** [comment]
True..

**Comment by revelt** [comment]
Should we close this and create an issue on VSCode repos instead? It's out of scope clearly...

**Comment by alohaas** [comment]
Hey guys, apologies for the late response. I'm glad you like the package @york-xtrem ! I have no plans to move this to VSCode. @revelt 's idea to open an issue on VSCode is probably the best way to go. 

Okay if I close this?

**Comment by revelt** [comment]
let's do it
